package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Wednesday, March 15, 2023 2:37:32 AM PDT
*/

public interface ReverseOperations 
{
  String reverse_string (String str);
} // interface ReverseOperations
